[phases.setup]
cmds = [
    "pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
]

[start]
cmd = "python manage.py migrate && gunicorn betweencoffee_delivery.wsgi:application --bind 0.0.0.0:$PORT"

[providers.python]
version = "3.8.13"